{{ if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  password: {{ .Values.mongodb.password | b64enc | quote}}
{{ end }}
