apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
      app.kubernetes.io/component: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        app.kubernetes.io/component: {{ .Values.app.name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mongodb
          image: public.ecr.aws/docker/library/python:3.13-slim
          command: ['sh', '-c']
          envFrom:
            - secretRef:
                name: mongo-credentials
          args:
            - |
              echo "Installing pymongo..."
              pip install --no-cache-dir pymongo

              echo "Waiting for MongoDB replica set to be ready..."
              python3 /app/wait.py
          volumeMounts:
            - mountPath: /app/wait.py
              name: script
              subPath: wait.py
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 7860
              name: registry
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.app.envSecretName }}
            {{- if eq (.Values.global.authProvider.type | default "keycloak") "keycloak" }}
            - secretRef:
                name: keycloak-client-secret
            {{- end }}
            - secretRef:
                name: mongo-credentials
            {{- if .Values.global.sharedSecretName }}
            - secretRef:
                name: {{ .Values.global.sharedSecretName }}
            {{- end }}
          env:
            - name: DEPLOYMENT_MODE
              value: {{ .Values.app.deploymentMode | default "with-gateway" | quote }}
            - name: REGISTRY_MODE
              value: {{ .Values.app.registryMode | default "full" | quote }}
      volumes:
        - name: script
          configMap:
            name: setup-mongodb
